### ISSUE TITLE
Some usage experience and feedback and thank you for such great work!

### ISSUE THREAD

**Issue by Gazoo101** [axjxwright/AX-MediaPlayer#3]
Further testing. I had some minor barriers with using the MediaPlayer object (likely due to my own bungling), so I opted to build the sample app, just to get a bit more insight.

It might be worth noting in your Git's readme.md that the sample app is Cinder 0.9.3 (or higher) only as it relies on `CinderImGui`, which isn't in Cinder 0.9.2.

I then compiled the latest Cinder 0.9.3 dev and found it still couldn't resolve the `CINDER_PATH` macro in the sample code? Is this an external define? Either way, I replaced it with a path and the sample compiles and plays the video. Excellent work. Really really good stuff. My impression is that hardware accelerated playback on Windows, when attempting to have the result end up on an OpenGL texture is quite the bother, so I can't emphasize enough how cool it is to see it all wrapped up in a simple to use library. Thanks again!

I really hope I can manage to integrate it with my Cinder 0.9.2 project. I'll try and figure out what's going on in my project that's making it not quite behave itself.

Two further thoughts on possible improvements:

1. It'd be great if the create function could accept a standard `std::string`. While it's totally understandable that the library would rely on Cinder based structs given that it's meant to only be used in Cinder, I often find sticking to the simplest data types preferrable, when possible. Simply because it eases the burden of knowing what's going on as a developer.

I realize turning a string into a `ci::DataSourcePath` is as simple as `ci::DataSourcePath::create( path_to_video )`. All the same I think it'd make the object even nicer to use.

2. Is there a particular reason why the library only allows the `MediaPlayer` to exist as a `shared_ptr`? I'm big on using `unique_ptr` to communicate exclusive ownership and would like to use the `MediaPlayer` as such, unless there's a reason it has to exist as a `shared_ptr`?

Maybe creating multiple `MediaPlayer`s is bad? I hope not, as I'm hoping to (on occasion) decode 2-3 videos simultaneously. Let me know your thoughts!

Again, great work!

**Comment by Gazoo101** [comment]
I've dug a bit deeper re. my usage of `MediaPlayer` in my application and have gotten wiser.

My application spawns the `MediaPlayer` and has an expectation of immediately querying the duration of the video. Tracking the duration value in the player changing, I can see in the code that `MediaPlayer` is awaiting notification from Windows (I think?) to trigger the `MF_MEDIA_ENGINE_EVENT_DURATIONCHANGE` event.

I can simply poll the duration of the video and hold off the rest of my application until it changes from 0.0 to something more credible. Not ideal, but certainly functional.

I thought I'd ask if you were open to exposing either a callback to the duration being set, or perhaps a more user friendly emit called `loaded`/`loadComplete` or something, signalling that the `MediaPlayer` now has all of its values ready?

I'd favor the latter, simply because it saves the caller from understanding the internals, but still signals that constructing the `MediaPlayer` leads to partially a-synchronous behavior. I.e. it isn't fully ready on construction. Providing a blocking load/constructor would also be an option.

Looking forward to hearing your thoughts.

**Comment by axjxwright** [comment]
Lots to get to here, thanks for the detailed report. 

1. Good point about the inbuilt imgui with 0.9.3. I actually don't use cinder's bundled imgui myself either since imgui is updated so frequently it seems foolish to be locked to an old version. I'll either conditionally compile the imgui code out or make a note that the sample is 0.9.3+ only.

2. The `CINDER_PATH` macro is injected by the sample cmake script [here](https://github.com/axjxwright/AX-MediaPlayer/blob/master/samples/SimplePlayback/proj/cmake/CMakeLists.txt#L19). This was just so I didn't have to provide a sample video and could just use one that comes with cinder. 

3. Taking a `DataSourceRef` was a specific choice, as it removes all the ambiguities between assets, files and urls. Forcing the user to wrap their string in `loadAsset` or `loadUrl` is a small price to pay for the benefits at the other end. I'd be comfortable accepting a `fs::path` as that is implied to be file system absolute path but a plain string is much too ambiguous for my tastes since we support both file system and networked sources

4. Using `shared_ptr` was more of a default choice based on my specific use case and also following idiomatic cinder style, but I don't see a problem with making it a `unique_ptr`. You can create many simultaneous players without issue but I use RAII heavily behind the scenes so it's important that it's heap allocated and managed a smart pointer to obviate the issues with copying and assignment etc
 
5. I'll add a signal that gets fired when that metadata is available. `OnReady`, most likely.

There shouldn't be anything stopping you from running in 0.9.2 as of the glload change the other day, but let me know if you hit any other roadblocks. Thanks again for putting it through its paces.

**Comment by axjxwright** [comment]
[This](https://github.com/axjxwright/AX-MediaPlayer/commit/b67359ac7a7c67b46ef8fbf37860c79a78ec4ee2) commit adds the `unique_ptr` change, the `OnReady` signal (and related `::IsReady()` accessor for polling purposes) as well as removing the requirement for ImGui in the sample.

**Comment by Gazoo101** [comment]
Appreciate the quick turn-around @axjxwright - I'll give the changes a spin as soon as I can.

All your feedback sounds reasonable. I'd be keen on a `fs::path` constructor if you can find the motivation to add that at at some point.

I was a bit surprised to see you opted to replace `shared_ptr` with `unique_ptr` rather than support both directly, although the nice thing about preferring `unique_ptr` over `shared_ptr` if only one is supported, is that a `unique_ptr` can easily be converted to a shared `shared_ptr`, but the other way around - not so much.

All that being said, if you do decide to stick with only explicitly supporting `unique_ptr` I would recommend tweaking the `MediaPlayerRef` short-hand to something else. Mostly because every single `<object>Ref` I've come across in Cinder is always a shared_ptr so the name used along with `unique_ptr` breaks this convention.

**Comment by axjxwright** [comment]
I've decided to revert to `shared_ptr` only as that is predictable behavior in a cinder code base and does the expected thing by default. The standard use case would be no different from a `unique_ptr` anyway and thus has zero performance penalty. 

Following that thinking, i've moved to a more common `Format()` pattern as opposed to the flags that were passed in the original version. e.g `MediaPlayer::Create ( loadUrl ( "...." ), MediaPlayer::Format().HardwareAccelerated ( ).AudioOnly ( ) )`

I've added an `fs::path` creation method too, but it will fail if it doesn't `::exist()` before i even kick off the heavy creation of the media player itself. 

Cheers

**Comment by Gazoo101** [comment]
I'm sure I follow what you mean when you say 'standard use case'. To me, the benefits of allowing unique_ptr version is mostly to communicate ownership. I personally try to limit my use of `shared_ptr` unless necessary, as it can be a one size fits all solution which I find tricky to manage.

Using the `Format()` approach makes sense. I've applied chaining to my own code base too.

Thanks @axjxwright 

For some motivation, I thought I'd toss you a quick demo usage of your library: https://youtu.be/P9WwkraAQD0
The work is far from complete as the code is fairly spaghetti, but I hope to clean it up a fair bit soon.

Have you thought about what license you'd like to put your code under?

**Comment by axjxwright** [comment]
That's great, happy to see it merged without too much friction.

I hadn't thought about licensing, but I'll have a look and assign one, probably MIT or public domain, I'd say.
