### ISSUE TITLE
Framelease is empty by new load of Videofile

### ISSUE THREAD

**Issue by KurtKomell** [axjxwright/AX-MediaPlayer#9]
Hi, the Framelease is empty when i try to relaod the videofile second time. What can i do?

**Comment by axjxwright** [comment]
Can you post a code sample and upload the video somewhere please?

**Comment by KurtKomell** [comment]
I declare the Mediaplayervariables:

```
protected:
	AX::Video::MediaPlayer::Error _error{ AX::Video::MediaPlayer::Error::NoError };
	bool _hardwareAccelerated{ true };
	bool _approximateSeeking{ true };
	AX::Video::MediaPlayerRef mMediaPlayer;

```
then i load the video from a moviepath to the player in a seprate funktion

```
AX::Video::MediaPlayerRef VidesizerApp::loadMovieseetings(fs::path movie)
{
	AX::Video::MediaPlayerRef _player;
	auto fmt = AX::Video::MediaPlayer::Format().HardwareAccelerated(_hardwareAccelerated);
	_player = AX::Video::MediaPlayer::Create(movie, fmt);
	_player->SetLoop(true);
	connectSignals(_player);
	_player->Play();
	return _player;
}
```

then i call the funtion and try to create a texture from it.

```
mMediaPlayer = loadMovieseetings(moviePath);


if (mMediaPlayer->IsHardwareAccelerated())
{
	// You can still use this method in software rendered mode
	// but it will create a new texture every time it's called
	// even if ::CheckNewFrame() was false. Use the above method 
	// for optimal texture creation in software mode but if you 
	// don't care, this block is functionally identical in both paths
	if (auto lease = mMediaPlayer->GetTexture())
	{
		// You can now use this texture until `lease` goes out
		// of scope (it will Unlock() the texture when destructing )
		gl::draw(*lease, getWindowBounds());
		texture = *lease;
	}
}
```
 the mediaplayer is attached but the framelease is empty.

What do you think? What do i wrong?.

**Comment by axjxwright** [comment]
Typically you want to create the player once (`loadMovieseetings` in your case) in a setup function and then draw it in your app's `draw` function. Are you loading a video and then immediately trying to draw it like this code suggests?

Also, it looks like you may be trying to keep a local copy of the texture for later which you're not allowed to do. The reason there's a `FrameLease` in the first place is because you're _leasing_ (borrowing) the player's internal shared texture memory and can therefore only draw it while you own the lease. If you want a copy you'll need to explicitly copy the texture data into your own texture while you hold the frame lease, and then you can use _that_ texture however you like.

**Comment by KurtKomell** [comment]
even if i try to draw the lease it is null no matter what i do with it afterwards. this is also the case if i run the example programm and use the dropfile function. 

Can I copy the texture via lease -> toTexture?

**Comment by KurtKomell** [comment]
When I load it for the first time, it also works when I fill the media player in the setup. Only when I want to fill the media player again with a function does it not work.

**Comment by axjxwright** [comment]
I've just dragged multiple videos into the test application and it works fine, so either there's something wrong with the specific video you're using, or there's something wrong with your code. I'm happy to make reasonable efforts to help you but unless there's something buggy in the player code itself I'm going to close this issue.

> Can I copy the texture via lease -> toTexture?

No, that's an explicit function that you were using via operator overloading normally. If you don't use hardware acceleration, the texture returned to you is yours to do with what you please, because it creates a new texture on demand, in hardware accelerated mode you're just borrowing the memory owned by directx so you can only draw it in the brief window you have ownership of it (via the lease).

If you want to upload the video you're using somewhere I'm happy to test it, otherwise i can't see the issue you're having, i'm afraid.
